### ISSUE TITLE
I want the output of module commonjs, where to set

### ISSUE THREAD

**Issue by ape-casear** [guoyunhe/swc-minifier-webpack-plugin#13]
你好，我想使用这个minify替换掉webpack5中的terser, 但是使用这个swc-minify输出的esmodule的，我想要commonjs格式的应该怎么配置的呢，这个插件好像也没有读取.swcrc的内容

**Comment by guoyunhe** [comment]
请提供复现代码 repo

**Comment by ape-casear** [comment]
> 请提供复现代码 repo

我弄一个只有webpack5和swc的demo确实没问题。

我项目里的报错是这样的，我再看看报错的路径找找原因
Caused by:
    0: failed to parse input file
    1: Syntax Error
    at makeWebpackError (node_modules\webpack\lib\HookWebpackError.js:48:9)
    at node_modules\webpack\lib\Compilation.js:3204:12
    at eval (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:44:1)
-- inner error --
Error:   × 'import', and 'export' cannot be used outside of module code

**Comment by ape-casear** [comment]
我的问题，static有个js文件，既引用到项目里，又copy到dist的static下面，static/dist下的就是es的，然后不知道为啥就报了上面的错误，我处理掉这个文件就好了
